#!/usr/bin/env node
// Renders the app icon artwork into every PNG the web app and the Android build need.
//
//   node scripts/make-icons.mjs
//
// Sources (hand-drawn SVG, edit these):
//   assets/icon.svg             full-bleed icon: velvet, brass coaster ring, lipstick kiss, spark
//   assets/icon-foreground.svg  the same mark on a transparent canvas, inside the adaptive-icon
//                               safe zone (Android launchers mask and move it)
//
// Outputs (commit them; CI does not run this script):
//   public/favicon.svg, public/icons/icon.svg   rounded-square SVG favicon
//   public/icons/favicon-32.png                 rounded, for browsers without SVG favicons
//   public/icons/icon-192.png, icon-512.png     PWA "any" icons (rounded, transparent corners)
//   public/icons/icon-maskable-512.png          PWA maskable icon (full bleed)
//   public/icons/apple-touch-icon-180.png       full bleed (iOS rounds it and shows alpha as black)
//   public/icons/apple-touch-icon.png           same picture under the name index.html uses
//   assets/android/res/**                       Android launcher icons and the splash icon. The
//                                               Android CI job copies this folder over the res/ of
//                                               the generated project (see .github/workflows).
//   assets/icon-only.png, icon-foreground.png, icon-background.png (1024)
//   assets/splash.png, splash-dark.png (2732)   the same art in the layout @capacitor/assets expects,
//                                               kept for other tools. CI doesn't use them: that tool
//                                               insets the adaptive layers by 16.7% with a 48dp
//                                               bitmap (blurry and small on xxhdpi screens) and adds
//                                               about 3 MB of splash bitmaps the launch theme never
//                                               shows.
//
// Android resources written to assets/android/res/:
//   mipmap-<density>/ic_launcher.png             legacy icon (Android 7), rounded square in 48dp
//   mipmap-<density>/ic_launcher_round.png       legacy round icon (Android 7.1)
//   mipmap-<density>/ic_launcher_foreground.png  adaptive foreground, 108dp, mark inside the safe zone
//   mipmap-<density>/ic_launcher_monochrome.png  themed icon (Android 13), white silhouette
//   mipmap-anydpi-v26/ic_launcher{,_round}.xml   adaptive icon: velvet + foreground + monochrome
//   values/ic_launcher_background.xml            the velvet background color
//   drawable-<density>/crush_splash_icon.png     Android 12+ splash icon, 288dp (mark inside the
//                                               192dp circle the system masks it to)
//
// PNGs are drawn by the e2e Chromium through playwright-core (CHROMIUM_PATH overrides it).

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { chromium } from 'playwright-core'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const ASSETS = path.join(ROOT, 'assets')
const PUBLIC = path.join(ROOT, 'public')
const ICONS = path.join(PUBLIC, 'icons')
const CHROMIUM = process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium'

const ANDROID_RES = path.join(ASSETS, 'android', 'res')

const VELVET = '#2A0F1F'
/** Corner radius of the rounded-square variants, as a share of the side (Android-like squircle). */
const ROUND = 0.225
/** Mark size on the splash images, as a share of the side (the foreground art keeps its margin). */
const SPLASH_MARK = 0.42
/** Android density buckets and their px per dp. */
const DENSITIES = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 }

// The adaptive icon, with a monochrome layer for Android 13 themed icons.
const ADAPTIVE_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/make-icons.mjs. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>
</adaptive-icon>
`
const BACKGROUND_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/make-icons.mjs. Velvet, behind the adaptive icon foreground. -->
<resources>
    <color name="ic_launcher_background">${VELVET}</color>
</resources>
`

const icon = await readFile(path.join(ASSETS, 'icon.svg'), 'utf8')
const foreground = await readFile(path.join(ASSETS, 'icon-foreground.svg'), 'utf8')

/** The icon clipped to a rounded square, as a standalone SVG (favicon). */
function roundedSvg(svg) {
  const inner = svg.replace(/<\?xml[^>]*>\s*/, '').trim()
  const r = Math.round(1024 * ROUND)
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <!-- Generated from assets/icon.svg by scripts/make-icons.mjs. Edit the source, not this file. -->
  <defs><clipPath id="cl-round"><rect width="1024" height="1024" rx="${r}"/></clipPath></defs>
  <g clip-path="url(#cl-round)">
${inner}
  </g>
</svg>
`
}

const dataUri = (svg) => `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`

/**
 * Screenshot one picture: an optional solid background with an SVG centered on it.
 * `art` is the SVG's size in px (defaults to the whole canvas), `radius` rounds its corners (0.5
 * makes a circle), `filter` is a CSS filter applied to the art.
 */
async function render(
  page,
  file,
  { svg, size, art = size, radius = 0, filter = 'none', background = 'transparent' },
) {
  await mkdir(path.dirname(file), { recursive: true })
  await page.setViewportSize({ width: size, height: size })
  const img = svg
    ? `<img src="${dataUri(svg)}" width="${art}" height="${art}" style="display:block;border-radius:${radius * art}px;filter:${filter}">`
    : ''
  await page.setContent(
    `<!doctype html><html style="background:transparent"><body style="margin:0;width:${size}px;height:${size}px;display:grid;place-items:center;background:${background}">${img}</body></html>`,
  )
  if (svg) await page.locator('img').evaluate((el) => el.decode())
  await page.screenshot({
    path: file,
    omitBackground: background === 'transparent',
    clip: { x: 0, y: 0, width: size, height: size },
  })
  console.log(`wrote ${path.relative(ROOT, file)} (${size}x${size})`)
}

await mkdir(ICONS, { recursive: true })
const rounded = roundedSvg(icon)
for (const file of [path.join(PUBLIC, 'favicon.svg'), path.join(ICONS, 'icon.svg')]) {
  await writeFile(file, rounded)
  console.log(`wrote ${path.relative(ROOT, file)}`)
}

const browser = await chromium.launch({ executablePath: CHROMIUM, args: ['--no-sandbox'] })
try {
  const page = await browser.newPage({ deviceScaleFactor: 1 })
  const at = (dir, name) => path.join(dir, name)

  // Web and PWA.
  await render(page, at(ICONS, 'favicon-32.png'), { svg: icon, size: 32, radius: ROUND })
  await render(page, at(ICONS, 'icon-192.png'), { svg: icon, size: 192, radius: ROUND })
  await render(page, at(ICONS, 'icon-512.png'), { svg: icon, size: 512, radius: ROUND })
  await render(page, at(ICONS, 'icon-maskable-512.png'), { svg: icon, size: 512 })
  await render(page, at(ICONS, 'apple-touch-icon-180.png'), { svg: icon, size: 180 })
  await render(page, at(ICONS, 'apple-touch-icon.png'), { svg: icon, size: 180 })

  // Sources for @capacitor/assets (Android launcher icons and splash).
  await render(page, at(ASSETS, 'icon-only.png'), { svg: icon, size: 1024 })
  await render(page, at(ASSETS, 'icon-foreground.png'), { svg: foreground, size: 1024 })
  await render(page, at(ASSETS, 'icon-background.png'), { size: 1024, background: VELVET })
  const splash = { svg: foreground, size: 2732, art: Math.round(2732 * SPLASH_MARK), background: VELVET }
  await render(page, at(ASSETS, 'splash.png'), splash)
  // The app is always dark, so the night splash is the same picture.
  await render(page, at(ASSETS, 'splash-dark.png'), splash)

  // Android resources, ready to copy over android/app/src/main/res/.
  await rm(ANDROID_RES, { recursive: true, force: true })
  for (const [density, scale] of Object.entries(DENSITIES)) {
    const mipmap = path.join(ANDROID_RES, `mipmap-${density}`)
    const legacy = Math.round(48 * scale)
    // Legacy icons keep the classic 2dp margin inside their 48dp box.
    const legacyArt = Math.round(44 * scale)
    await render(page, at(mipmap, 'ic_launcher.png'), { svg: icon, size: legacy, art: legacyArt, radius: ROUND })
    await render(page, at(mipmap, 'ic_launcher_round.png'), { svg: icon, size: legacy, art: legacyArt, radius: 0.5 })
    const adaptive = Math.round(108 * scale)
    await render(page, at(mipmap, 'ic_launcher_foreground.png'), { svg: foreground, size: adaptive })
    await render(page, at(mipmap, 'ic_launcher_monochrome.png'), {
      svg: foreground,
      size: adaptive,
      filter: 'brightness(0) invert(1)',
    })
    const drawable = path.join(ANDROID_RES, `drawable-${density}`)
    await render(page, at(drawable, 'crush_splash_icon.png'), { svg: foreground, size: Math.round(288 * scale) })
  }
  const anydpi = path.join(ANDROID_RES, 'mipmap-anydpi-v26')
  const values = path.join(ANDROID_RES, 'values')
  await mkdir(anydpi, { recursive: true })
  await mkdir(values, { recursive: true })
  for (const [file, text] of [
    [at(anydpi, 'ic_launcher.xml'), ADAPTIVE_XML],
    [at(anydpi, 'ic_launcher_round.xml'), ADAPTIVE_XML],
    [at(values, 'ic_launcher_background.xml'), BACKGROUND_XML],
  ]) {
    await writeFile(file, text)
    console.log(`wrote ${path.relative(ROOT, file)}`)
  }
} finally {
  await browser.close()
}
